<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.37">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Khaliun Battogtokh">
<meta name="dcterms.date" content="2026-05-01">

<title>Did ChatGPT Reshape Entry-Level Job Postings?</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="paper_draft_final_v2_files/libs/clipboard/clipboard.min.js"></script>
<script src="paper_draft_final_v2_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="paper_draft_final_v2_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="paper_draft_final_v2_files/libs/quarto-html/popper.min.js"></script>
<script src="paper_draft_final_v2_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="paper_draft_final_v2_files/libs/quarto-html/anchor.min.js"></script>
<link href="paper_draft_final_v2_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="paper_draft_final_v2_files/libs/quarto-html/quarto-syntax-highlighting-7f8f88aac4f3542376d5c11b86a4c14d.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="paper_draft_final_v2_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="paper_draft_final_v2_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="paper_draft_final_v2_files/libs/bootstrap/bootstrap-818f5057cbd7b03ce04bae1755a021b3.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction"><span class="header-section-number">1</span> Introduction</a></li>
  <li><a href="#data" id="toc-data" class="nav-link" data-scroll-target="#data"><span class="header-section-number">2</span> Data</a>
  <ul class="collapse">
  <li><a href="#job-postings-lightcast-emsi" id="toc-job-postings-lightcast-emsi" class="nav-link" data-scroll-target="#job-postings-lightcast-emsi"><span class="header-section-number">2.1</span> Job Postings: Lightcast (EMSI)</a>
  <ul class="collapse">
  <li><a href="#entry-level-definition" id="toc-entry-level-definition" class="nav-link" data-scroll-target="#entry-level-definition"><span class="header-section-number">2.1.1</span> Entry-Level Definition</a></li>
  </ul></li>
  <li><a href="#ai-exposure-measures" id="toc-ai-exposure-measures" class="nav-link" data-scroll-target="#ai-exposure-measures"><span class="header-section-number">2.2</span> AI Exposure Measures</a></li>
  </ul></li>
  <li><a href="#empirical-strategy" id="toc-empirical-strategy" class="nav-link" data-scroll-target="#empirical-strategy"><span class="header-section-number">3</span> Empirical Strategy</a>
  <ul class="collapse">
  <li><a href="#specification" id="toc-specification" class="nav-link" data-scroll-target="#specification"><span class="header-section-number">3.1</span> Specification</a></li>
  <li><a href="#identifying-assumption-and-rate-sensitivity-control" id="toc-identifying-assumption-and-rate-sensitivity-control" class="nav-link" data-scroll-target="#identifying-assumption-and-rate-sensitivity-control"><span class="header-section-number">3.2</span> Identifying Assumption and Rate Sensitivity Control</a></li>
  </ul></li>
  <li><a href="#results" id="toc-results" class="nav-link" data-scroll-target="#results"><span class="header-section-number">4</span> Results</a>
  <ul class="collapse">
  <li><a href="#posting-declines-are-sharpest-at-entry-level-software-developers" id="toc-posting-declines-are-sharpest-at-entry-level-software-developers" class="nav-link" data-scroll-target="#posting-declines-are-sharpest-at-entry-level-software-developers"><span class="header-section-number">4.1</span> Posting Declines Are Sharpest at Entry Level: Software Developers</a></li>
  <li><a href="#same-pattern-in-finance-investment-analysis" id="toc-same-pattern-in-finance-investment-analysis" class="nav-link" data-scroll-target="#same-pattern-in-finance-investment-analysis"><span class="header-section-number">4.2</span> Same Pattern in Finance &amp; Investment Analysis</a></li>
  <li><a href="#overall-entry-level-postings-have-not-recovered" id="toc-overall-entry-level-postings-have-not-recovered" class="nav-link" data-scroll-target="#overall-entry-level-postings-have-not-recovered"><span class="header-section-number">4.3</span> Overall Entry-Level Postings Have Not Recovered</a></li>
  <li><a href="#decline-concentrated-in-automating-occupations" id="toc-decline-concentrated-in-automating-occupations" class="nav-link" data-scroll-target="#decline-concentrated-in-automating-occupations"><span class="header-section-number">4.4</span> Decline Concentrated in Automating Occupations</a></li>
  <li><a href="#event-study-did-the-effect-begin-at-launch" id="toc-event-study-did-the-effect-begin-at-launch" class="nav-link" data-scroll-target="#event-study-did-the-effect-begin-at-launch"><span class="header-section-number">4.5</span> Event Study: Did the Effect Begin at Launch?</a></li>
  <li><a href="#did-regression-results" id="toc-did-regression-results" class="nav-link" data-scroll-target="#did-regression-results"><span class="header-section-number">4.6</span> DiD Regression Results</a></li>
  </ul></li>
  <li><a href="#discussion-and-limitations" id="toc-discussion-and-limitations" class="nav-link" data-scroll-target="#discussion-and-limitations"><span class="header-section-number">5</span> Discussion and Limitations</a>
  <ul class="collapse">
  <li><a href="#what-the-results-suggest" id="toc-what-the-results-suggest" class="nav-link" data-scroll-target="#what-the-results-suggest"><span class="header-section-number">5.1</span> What the Results Suggest</a></li>
  <li><a href="#limitations" id="toc-limitations" class="nav-link" data-scroll-target="#limitations"><span class="header-section-number">5.2</span> Limitations</a></li>
  </ul></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion"><span class="header-section-number">6</span> Conclusion</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references"><span class="header-section-number">7</span> References</a></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Did ChatGPT Reshape Entry-Level Job Postings?</h1>
<p class="subtitle lead">Evidence from AI Exposure and Job Postings Data</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Khaliun Battogtokh </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">May 1, 2026</p>
    </div>
  </div>
  
    
  </div>
  
<div>
  <div class="abstract">
    <div class="block-title">Abstract</div>
    <p>This paper examines whether the public release of ChatGPT in October 2022 reduced entry-level hiring in occupations highly exposed to generative AI. Using monthly job postings data from Lightcast (2020–2024) across 733 occupations, I document four findings. First, in software development , a high-AI-exposure occupation , entry-level postings fell to 56% of their October 2022 level by end of study, 2.4× harder than senior postings (81%). Second, across all occupations, overall entry-level postings have not recovered to pre-2022 levels while high-experience postings continued to grow. Third, a continuous-treatment difference-in-differences model finds that high-AI occupations saw a ≈ −2.4 percentage point decline in entry-level share post-ChatGPT, significant at the 5% level after controlling for each occupation’s sensitivity to interest rate changes. Fourth, the decline is concentrated in automating occupations; augmenting occupations show a different pattern. Together, the results suggest AI exposure may be compressing the entry tier of labor demand in ways that fall hardest on workers who rely on entry-level roles to build careers.</p>
  </div>
</div>


</header>


<section id="introduction" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Introduction</h1>
<p>In November 2022, OpenAI launched ChatGPT , and within weeks it became the fastest-growing consumer application in history. The launch marked a discrete and widely recognized break in the accessibility of generative AI to both employers and workers. Employers across industries began experimenting with AI tools for drafting, coding, data processing, and customer interaction , tasks that had, until recently, been the domain of entry-level workers building foundational skills.</p>
<p>This paper asks a narrow but consequential question: <strong>Did the ChatGPT launch reduce the share of job postings that are entry-level in occupations more exposed to AI?</strong> The motivation is straightforward. If generative AI can perform the tasks assigned to junior hires , drafting correspondence, writing code, summarizing documents, answering routine inquiries , then firms may respond at the margin not by laying off incumbents but by simply posting fewer entry-level roles. The hiring funnel narrows. Workers who were never hired are invisible in employment statistics, yet their exclusion is economically real.</p>
<p><strong>Why job postings?</strong> Job postings capture employer intent before a hire is made. If a firm knows AI can perform certain tasks faster and at lower cost, the first observable response is a change in <em>who they look for</em> , before any layoff or headcount reduction shows up in employment data. This makes postings a leading indicator of AI’s effect on labor demand composition.</p>
<p>The remainder of the paper proceeds as follows. Section 2 describes the data sources. Section 3 presents the empirical strategy. Section 4 reports results. Section 5 discusses limitations. Section 6 concludes.</p>
<hr>
</section>
<section id="data" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Data</h1>
<section id="job-postings-lightcast-emsi" class="level2" data-number="2.1">
<h2 data-number="2.1" class="anchored" data-anchor-id="job-postings-lightcast-emsi"><span class="header-section-number">2.1</span> Job Postings: Lightcast (EMSI)</h2>
<p>The primary data source is the Lightcast (formerly EMSI Burning Glass) job postings database, covering approximately 92% of all U.S. online job postings from January 2020 through December 2024. Each posting includes the occupation code (5-digit SOC 2021), posting and expiration dates, minimum years of experience required, education requirement, and a standardized seniority label assigned by Lightcast (<code>Intermediate</code>, <code>Junior</code>, or <code>Senior</code>).</p>
<p>To validate the series, I compare Lightcast monthly posting counts to BLS JOLTS total nonfarm job openings over the same period. Figure 1 shows that Lightcast closely tracks JOLTS in level and trend, providing confidence the postings data captures genuine labor demand fluctuations rather than scraping artifacts.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../slide_figures/jolts_validation.png" class="img-fluid figure-img" style="width:90.0%"></p>
<figcaption>Figure 1: Lightcast job postings closely track BLS JOLTS job openings (2020–2024)</figcaption>
</figure>
</div>
<p>The analysis focuses on monthly occupation-level panels. After filtering to occupations with sufficient volume (&gt; 100 postings per month), the panel covers <strong>733 five-digit SOC occupations</strong> and 63 months (January 2020 – March 2025), yielding approximately 45,000 occupation × month observations.</p>
<section id="entry-level-definition" class="level3" data-number="2.1.1">
<h3 data-number="2.1.1" class="anchored" data-anchor-id="entry-level-definition"><span class="header-section-number">2.1.1</span> Entry-Level Definition</h3>
<p>A posting is classified as <strong>entry-level</strong> if it satisfies two conditions:</p>
<ol type="1">
<li><p><strong>Experience requirement</strong>: <code>min_years_experience ≤ 2</code>, <em>or</em> (<code>job_seniority_name = 'Junior'</code> and <code>min_years_experience IS NULL</code>). The Junior + NULL carve-out is grounded in Lightcast’s classifier design. The seniority classifier is high-precision, low-recall: Junior labels are reliable positive identifiers of entry-level roles. Seniority values are fully populated in the 2020–2024 data (Intermediate: 83.6%, Junior: 9.2%, Senior: 7.2%; no missing values).</p></li>
<li><p><strong>Education requirement</strong>: At most a bachelor’s degree (<code>min_edulevels_name</code> ∈ {No Education Listed, High school or GED, Associate degree, Bachelor’s Degree}).</p></li>
</ol>
<p>This definition follows the Burning Glass (2021) standard of 0–2 years of required experience.</p>
</section>
</section>
<section id="ai-exposure-measures" class="level2" data-number="2.2">
<h2 data-number="2.2" class="anchored" data-anchor-id="ai-exposure-measures"><span class="header-section-number">2.2</span> AI Exposure Measures</h2>
<p><strong>Primary: <code>gpt4_beta</code> (Eloundou et al., 2023).</strong> This score reflects the fraction of an occupation’s O*NET tasks for which GPT-4 can provide meaningful assistance, as assessed by GPT-4 itself and human raters. The score ranges from 0 to 1 and is time-invariant by construction.</p>
<p><strong>Robustness: <code>observed_exposure</code> (Anthropic Economic Index).</strong> Derived from actual Claude usage patterns by occupation, reflecting revealed post-ChatGPT AI adoption. The two measures correlate at r = 0.638 (Spearman ρ = 0.699) across 630 occupations.</p>
<p><strong>Automation vs.&nbsp;augmentation (Brynjolfsson, Chandar &amp; Chen, 2025).</strong> The Anthropic Economic Index additionally classifies each occupation’s AI exposure as primarily <em>automating</em> (AI replaces tasks) or <em>augmenting</em> (AI complements workers). This distinction is used in the descriptive analysis to explain heterogeneity in the entry-level decline.</p>
<hr>
</section>
</section>
<section id="empirical-strategy" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Empirical Strategy</h1>
<section id="specification" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="specification"><span class="header-section-number">3.1</span> Specification</h2>
<p>The main estimating equation is a continuous-treatment difference-in-differences model with two-way fixed effects:</p>
<p><span class="math display">\[\text{entry\_sa}_{it} = \alpha + \beta \cdot (\text{Post}_t \times \text{GPT4Exp}_i) + \gamma_i + \delta_t + \varepsilon_{it}\]</span></p>
<p>where:</p>
<ul>
<li><span class="math inline">\(\text{entry\_sa}_{it}\)</span> is the seasonally adjusted entry-level share for occupation <span class="math inline">\(i\)</span> in month <span class="math inline">\(t\)</span> (percentage points)</li>
<li><span class="math inline">\(\text{Post}_t = \mathbf{1}[t \geq \text{October 2022}]\)</span> , ChatGPT launched November 30, 2022, the final day of the month, making November effectively a pre-treatment month in monthly data. Following Brynjolfsson, Chandar &amp; Chen (2025), October 2022 is used as the event reference month and normalization point</li>
<li><span class="math inline">\(\text{GPT4Exp}_i\)</span> is the GPT-4 exposure score (0–1), time-invariant</li>
<li><span class="math inline">\(\gamma_i\)</span> are occupation fixed effects, absorbing time-invariant level differences</li>
<li><span class="math inline">\(\delta_t\)</span> are year-month fixed effects, absorbing macro shocks common across occupations</li>
<li><span class="math inline">\(\beta\)</span> is the DiD coefficient of interest: for a 1-unit increase in AI exposure, how much more did the entry-level share fall post-ChatGPT?</li>
</ul>
<p>The model is estimated by WLS weighted by each occupation’s 2021 posting share, with standard errors clustered by occupation.</p>
</section>
<section id="identifying-assumption-and-rate-sensitivity-control" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="identifying-assumption-and-rate-sensitivity-control"><span class="header-section-number">3.2</span> Identifying Assumption and Rate Sensitivity Control</h2>
<p>The key identifying assumption is <strong>parallel trends</strong>: absent ChatGPT, entry-level shares would have trended similarly across high- and low-exposure occupations. The event study (Section 4.4) provides evidence for this assumption.</p>
<p>The primary identification threat is the <strong>2022–2023 interest rate cycle</strong>: the Fed raised the federal funds rate from near zero to over 5% precisely as ChatGPT launched. Time fixed effects absorb the aggregate rate level, but do not account for the fact that some occupations are more rate-sensitive than others. To address this, I construct a pre-period rate sensitivity measure for each occupation , the OLS coefficient from regressing each occupation’s monthly posting % change on the change in the FFR over 2020–2022 , and add it as an interaction <code>post × rate_sensitivity_i</code> in a robustness specification.</p>
<hr>
</section>
</section>
<section id="results" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Results</h1>
<section id="posting-declines-are-sharpest-at-entry-level-software-developers" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="posting-declines-are-sharpest-at-entry-level-software-developers"><span class="header-section-number">4.1</span> Posting Declines Are Sharpest at Entry Level: Software Developers</h2>
<p>Figure 2 shows monthly job postings for Software Developers (GPT-4 exposure = 0.94), a high-AI-exposure occupation, broken out by experience bucket and indexed to October 2022 = 1.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../slide_figures/swd_yoe_3bucket.png" class="img-fluid figure-img" style="width:90.0%"></p>
<figcaption>Figure 2: Software Developer postings by YOE bucket, indexed to Oct 2022 = 1 (3-month centered moving average)</figcaption>
</figure>
</div>
<p>The pattern is striking. By end of the study period:</p>
<ul>
<li><strong>Entry-level (0–3 YOE)</strong> fell to <strong>56%</strong> of its October 2022 level</li>
<li><strong>Mid-level (4–6 YOE)</strong> fell to <strong>66%</strong></li>
<li><strong>Senior (7+ YOE)</strong> fell to <strong>81%</strong></li>
</ul>
<p>Entry-level postings fell <strong>2.4× harder</strong> than senior postings. This is consistent with Brynjolfsson et al.&nbsp;(2025), who document using ADP payroll data that early-career workers in AI-exposed occupations experienced 16% relative employment declines.</p>
</section>
<section id="same-pattern-in-finance-investment-analysis" class="level2" data-number="4.2">
<h2 data-number="4.2" class="anchored" data-anchor-id="same-pattern-in-finance-investment-analysis"><span class="header-section-number">4.2</span> Same Pattern in Finance &amp; Investment Analysis</h2>
<p>Figure 3 replicates the pattern for Financial and Investment Analysts (another high-AI-exposure occupation).</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../slide_figures/yoe_finanalysts.png" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption>Figure 3: Financial and Investment Analyst postings by YOE bucket, indexed to Oct 2022 = 1</figcaption>
</figure>
</div>
<p>Senior postings reached <strong>110%</strong> of their October 2022 level while entry-level and mid-level postings remain at <strong>78%</strong>. The divergence between senior and entry-level within the same occupation points to a compositional shift in demand , not just an aggregate decline.</p>
</section>
<section id="overall-entry-level-postings-have-not-recovered" class="level2" data-number="4.3">
<h2 data-number="4.3" class="anchored" data-anchor-id="overall-entry-level-postings-have-not-recovered"><span class="header-section-number">4.3</span> Overall Entry-Level Postings Have Not Recovered</h2>
<p>Figure 4 shows total monthly postings across all occupations, broken into four experience buckets.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../slide_figures/postings_by_yoe_fact2_4bucket.png" class="img-fluid figure-img" style="width:85.0%"></p>
<figcaption>Figure 4: Total postings by YOE bucket across all occupations (indexed to Oct 2022 = 1)</figcaption>
</figure>
</div>
<p>Postings requiring 0–3 YOE and 4–6 YOE declined after ChatGPT’s launch and have not recovered. Only the highest-experience group (11+ YOE) has grown substantially. The pattern holds across the full economy, not just in software or finance.</p>
</section>
<section id="decline-concentrated-in-automating-occupations" class="level2" data-number="4.4">
<h2 data-number="4.4" class="anchored" data-anchor-id="decline-concentrated-in-automating-occupations"><span class="header-section-number">4.4</span> Decline Concentrated in Automating Occupations</h2>
<p>Figure 5 splits occupations by whether their AI exposure is primarily <em>automating</em> (AI replaces tasks) or <em>augmenting</em> (AI complements workers), following Brynjolfsson, Chandar &amp; Chen (2025).</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../slide_figures/canaries_entry_auto_aug.png" class="img-fluid figure-img" style="width:95.0%"></p>
<figcaption>Figure 5: Entry-level posting trends by AI exposure quintile , automating (left) vs.&nbsp;augmenting (right) occupations</figcaption>
</figure>
</div>
<p>In automating occupations (left panel), darker lines (higher AI exposure quintiles) fall furthest after October 2022 , consistent with AI substituting entry-level tasks and reducing the need to hire junior workers. In augmenting occupations (right panel), the pattern reverses: higher-exposure quintiles hold up better or grow, consistent with firms seeking more workers as AI multiplies their productivity. This heterogeneity is important: the aggregate decline in entry-level hiring is not uniform , it is driven by the automating end of the AI exposure spectrum.</p>
</section>
<section id="event-study-did-the-effect-begin-at-launch" class="level2" data-number="4.5">
<h2 data-number="4.5" class="anchored" data-anchor-id="event-study-did-the-effect-begin-at-launch"><span class="header-section-number">4.5</span> Event Study: Did the Effect Begin at Launch?</h2>
<p>The event study tests whether the divergence between high- and low-exposure occupations began precisely at ChatGPT’s launch or whether the groups were already trending apart beforehand.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../slide_figures/event_study_main.png" class="img-fluid figure-img" style="width:90.0%"></p>
<figcaption>Figure 6: Event study , monthly DiD coefficients under both exposure measures (left: gpt4_beta; right: Anthropic observed exposure). Main entry-level definition, N = 678 occupations, balanced panel, reference month: Oct 2022</figcaption>
</figure>
</div>
<p>Pre-treatment coefficients are noisy but centered near zero, providing support for the parallel trends assumption: high- and low-exposure occupations were on similar trajectories before October 2022. Post-treatment coefficients turn negative immediately after launch and remain negative, consistent with the gap opening at ChatGPT’s introduction and persisting through the post-period.</p>
</section>
<section id="did-regression-results" class="level2" data-number="4.6">
<h2 data-number="4.6" class="anchored" data-anchor-id="did-regression-results"><span class="header-section-number">4.6</span> DiD Regression Results</h2>
<p>Table 1 reports the main DiD estimates and robustness checks.</p>
<p><strong>Table 1: DiD Estimates , Post × AI Exposure on Entry-Level Share</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
</colgroup>
<thead>
<tr class="header">
<th>Specification</th>
<th>Treatment</th>
<th>Coef.</th>
<th>Std. Err.</th>
<th>p-value</th>
<th>95% CI</th>
<th>N obs</th>
<th>N occ</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>(1) Main DiD</strong></td>
<td><code>gpt4_beta</code></td>
<td><strong>−1.729</strong></td>
<td>0.898</td>
<td>0.054</td>
<td>[−3.49, 0.03]</td>
<td>45,436</td>
<td>733</td>
</tr>
<tr class="even">
<td><strong>(2) + rate sensitivity</strong></td>
<td><code>gpt4_beta</code></td>
<td><strong>−1.926</strong></td>
<td>0.824</td>
<td><strong>0.019</strong></td>
<td>[−3.54, −0.31]</td>
<td>45,186</td>
<td>729</td>
</tr>
<tr class="odd">
<td><strong>(3) Main DiD</strong></td>
<td><code>observed_exposure</code></td>
<td><strong>−2.243</strong></td>
<td>0.921</td>
<td><strong>0.015</strong></td>
<td>[−4.05, −0.44]</td>
<td>44,403</td>
<td>716</td>
</tr>
<tr class="even">
<td><strong>(4) + rate sensitivity</strong></td>
<td><code>observed_exposure</code></td>
<td><strong>−2.426</strong></td>
<td>0.889</td>
<td><strong>0.006</strong></td>
<td>[−4.17, −0.68]</td>
<td>~44,100</td>
<td>~712</td>
</tr>
</tbody>
</table>
<p><em>All models: Y = seasonally adjusted entry-level share (%). WLS with 2021 posting weights, occupation + year-month FEs, SEs clustered by occupation. Rate sensitivity is the pre-period OLS coefficient from regressing each occupation’s monthly posting % change on ΔFFR (2020–2022). *p&lt;0.10, **p&lt;0.05, ***p&lt;0.01.</em></p>
<p>The main specification (Spec 1) yields β = <strong>−1.729 pp</strong> (p = 0.054). Adding the interest rate robustness control (Spec 2) <em>increases</em> the magnitude to <strong>−1.926 pp</strong> (p = 0.019). This is because AI-exposed occupations are <em>less</em> rate-sensitive (r = 0.047 between <code>gpt4_beta</code> and <code>rate_sensitivity</code>), meaning the 2022–23 rate cycle was slightly attenuating the AI estimate rather than inflating it. Disentangling rate sensitivity makes the AI signal cleaner.</p>
<p>Using the Anthropic Economic Index (<code>observed_exposure</code>) as the treatment measure yields larger and more precisely estimated effects: <strong>−2.243 pp</strong> (p = 0.015) and <strong>−2.426 pp</strong> (p = 0.006) in Specs 3 and 4. All four specifications are negative; three of four are significant at the 5% level.</p>
<p><strong>Benchmark:</strong> Software Developers (<code>gpt4_beta</code> = 0.94) versus Truck Drivers (<code>gpt4_beta</code> = 0.04) represent a 0.90-unit gap in treatment. Spec 2 implies a <strong>−1.73 percentage point</strong> differential decline in entry-level share for Software Developers relative to Truck Drivers after ChatGPT’s launch. A demand shock control was also tested and left the coefficient virtually unchanged (−1.729 → −1.732), confirming the result is not driven by sector-level hiring contractions.</p>
<hr>
</section>
</section>
<section id="discussion-and-limitations" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> Discussion and Limitations</h1>
<section id="what-the-results-suggest" class="level2" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="what-the-results-suggest"><span class="header-section-number">5.1</span> What the Results Suggest</h2>
<p>Taken together, the descriptive evidence and regression results tell a consistent story. Entry-level hiring has contracted most sharply in high-AI-exposure occupations , and the contraction is concentrated in the automating segment, where AI is most likely to substitute for junior-level tasks. This is not simply a tech sector story: the overall postings data show the entry-level shortfall across the full economy.</p>
<p>For workers who rely on entry-level roles as their primary path into a career, this compression represents a measurable narrowing of opportunity that does not show up in unemployment statistics. The concern is not displacement of experienced workers but exclusion of workers who never got the chance to become experienced.</p>
</section>
<section id="limitations" class="level2" data-number="5.2">
<h2 data-number="5.2" class="anchored" data-anchor-id="limitations"><span class="header-section-number">5.2</span> Limitations</h2>
<p><strong>1. Measurement of AI exposure.</strong> <code>gpt4_beta</code> measures what GPT-4 <em>could</em> do to an occupation’s tasks, not whether employers actually adopted AI. The score was constructed after ChatGPT’s launch using GPT-4 (released publicly March 2023), so it is not strictly pre-determined.</p>
<p><strong>2. Parallel trends.</strong> The pre-period (2020–2022) includes the COVID-19 shock and its uneven recovery, which may violate parallel trends independently of AI. The event study shows near-zero pre-trends, providing partial reassurance.</p>
<hr>
</section>
</section>
<section id="conclusion" class="level1" data-number="6">
<h1 data-number="6"><span class="header-section-number">6</span> Conclusion</h1>
<p>This paper documents four findings about how ChatGPT’s launch reshaped entry-level hiring:</p>
<ol type="1">
<li><p><strong>Entry-level postings fell 2.4× harder than senior</strong> in software developer job postings , the entry bucket declined to 56% of its October 2022 level while senior held at 81%.</p></li>
<li><p><strong>Overall entry-level postings have not recovered</strong> to pre-2022 levels across the full economy, while only the highest-experience group (11+ YOE) grew.</p></li>
<li><p><strong>High-AI occupations saw a ≈ −2.4 pp decline</strong> in entry-level share post-ChatGPT, significant at the 5% level after controlling for occupation-level interest rate sensitivity.</p></li>
<li><p><strong>The decline is concentrated in automating occupations</strong>; augmenting occupations show a different, more stable pattern , pointing to AI substitution, not general labor market weakness, as the driver.</p></li>
</ol>
<p>These findings do not settle the question of causality. Confounders cannot be fully ruled out, and the post-2022 period brought multiple overlapping shocks , the rate cycle, tech sector correction, and post-pandemic normalization. But the consistency of the results across exposure measures, specifications, and occupation types points in the same direction.</p>
<p>How this plays out over a longer horizon remains open. Prior technology transitions have ultimately created new categories of work even as they displaced old ones. Whether generative AI follows that pattern , or compresses the entry tier in ways that are more persistent , is a question the data will answer over time. What this paper documents is where we are right now.</p>
<hr>
</section>
<section id="references" class="level1" data-number="7">
<h1 data-number="7"><span class="header-section-number">7</span> References</h1>
<p>Eloundou, T., Manning, S., Mishkin, P., &amp; Rock, D. (2023). GPTs are GPTs: An early look at the labor market impact potential of large language models. <em>NBER Working Paper</em>.</p>
<p>Brynjolfsson, E., Chandar, B., &amp; Chen, S. (2025). Canaries in the coal mine? Six facts about the recent employment effects of artificial intelligence. <em>Stanford Digital Economy Lab Working Paper</em>.</p>
<p>Burning Glass Institute. (2023). <em>No Country for Young Grads: The decline in entry-level job postings is concentrated in roles highly exposed to AI.</em> The Burning Glass Institute.</p>
<p>Lightcast. (2024). <em>Job Postings Data</em>. Licensed to Opportunity@Work.</p>
<p>Lightcast. (2024). <em>Job Seniority</em>. Lightcast Knowledge Base. https://kb.lightcast.io/en/articles/11865067-job-seniority</p>
<p>Anthropic. (2024). <em>Anthropic Economic Index</em>. anthropic.com/economic-index.</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>